In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [7]:
x=np.array([5,15,25,35,45,55]).reshape(-1,1)
y=np.array([5,20,14,32,22,38])

In [8]:
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [12]:
model=LinearRegression()
model.fit(x,y)
LinearRegression(copy_X=True, fit_intercept=True,n_jobs=None,
normalize=False)
model=LinearRegression().fit(x,y)

In [14]:
r_sq=model.score(x,y)
print('coefficient of determiniation: ',r_sq)

coefficient of determiniation:  0.7158756137479542


In [15]:
print('intercept:', model.intercept_)
print('slope', model.coef_)


intercept: 5.633333333333329
slope [0.54]


In [16]:
new_model=LinearRegression().fit(x,y.reshape((-1,1)))
print('intercept:', new_model.intercept_)
print('slope', new_model.coef_)



intercept: [5.63333333]
slope [[0.54]]


In [17]:
y_pred=model.predict(x)
print('predicted response: ', y_pred, sep='\n')

predicted response: 
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
