In [1]:
import numpy as np

In [3]:
a=np.array ([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(a[0])

[1 2 3 4]


In [4]:
import numpy as np

In [5]:
a=np.array ([1,2,3,4])
a


array([1, 2, 3, 4])

In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
import numpy as np

In [15]:
print (np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [20]:
arr=np.array([1,2,3,4,5,6,7,8])

In [21]:
arr=np.append(arr,[1,2])

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [23]:
arr=np.delete(arr,1)

In [24]:
arr

array([1, 3, 4, 5, 6, 7, 8, 1, 2])

In [25]:
arr=np.array([2,1,5,3,7,4,6,8])

In [26]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [27]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
array_example=np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3,4],[5,6,7,8]]])

/var/folders/r_/0zt7_hb10179rdt5t_5rl9t80000gn/T/ipykernel_1206/2367092665.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_example=np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3,4],[5,6,7,8]]])


In [40]:
print(array_example)

[[list([0, 1, 2, 3]) list([4, 5, 6, 7])]
 [list([0, 1, 2, 3]) list([4, 5, 6, 7])]
 [list([0, 1, 2, 3, 4]) list([5, 6, 7, 8])]]


In [41]:
array_example.ndim

2

In [42]:
array_example.size

6

In [43]:
array_example.shape

(3, 2)

In [54]:
arr_one=np.array([[1,2,3,4,5]])

In [55]:
arr_one.ndim

2

In [56]:
arr_one.size

5

In [57]:
arr_one.shape

(1, 5)

In [59]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [60]:
b=a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [66]:
a.reshape(6,1)
a


array([0, 1, 2, 3, 4, 5])

In [67]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [69]:
a2=a[np.newaxis]
print (a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [72]:
row_vector=a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [74]:
col_vector=a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [75]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [76]:
b=np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [77]:
c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [79]:
data=np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [80]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [81]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12 13 14 15 16]


In [83]:
five_up=(a>=5)
print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12 13 14 15 16]
[ 5  6  7  8  9 10 11 12 13 14 15 16]


In [84]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12 14 16]
